app_forward_homepage:
    path:     /
    defaults: { _controller: AppForwardBundle:Default:index }


app_forward_alias_add:
    path:     /alias/add
    defaults: { _controller: AppForwardBundle:Alias:add }
