FROM ubuntu:trusty
MAINTAINER Vincent Mizoules, Alexandre Barret

# Update
RUN apt-get update
# Install
RUN apt-get -y install rsyslog postfix mailutils
RUN apt-get -y install postfix-mysql mysql-client

# Add files
ADD run.sh /opt/run.sh
RUN chmod +x /opt/run.sh

# Run CMD
CMD /opt/run.sh