FROM ubuntu:trusty
MAINTAINER Vincent Mizoules, Alexandre Barret

# Update
RUN apt-get update
# Install
RUN apt-get -y install rsyslog postfix mailutils
RUN apt-get -y install postfix-mysql mysql-client

# Add run
ADD run.sh /opt/run.sh
RUN chmod +x /opt/run.sh

# add config files
ADD etc/ /etc/
RUN chown -R postfix /etc/postfix && chgrp -R postfix /etc/postfix && chmod -R ugo+rwx /etc/postfix
RUN postmap /etc/postfix/virtual && postmap /etc/postfix/generic

# Run CMD
CMD /opt/run.sh