FROM ubuntu:trusty
MAINTAINER Vincent Mizoules, Alexandre Barret

# Update
RUN apt-get update
# Install
RUN apt-get -y install rsyslog postfix mailutils vim

# Add files
ADD run.sh /opt/run.sh
ADD config.sh /opt/config.sh

# End install
RUN chmod +x /opt/*.sh
RUN /opt/config.sh

# Run CMD
CMD /opt/run.sh