# dc rm -f && dc build && dc up

postfix:
    build: postfix_server
    hostname: localhost
    ports:
        - "25:25"
    volumes:
        - ./postfix_server/etc/postfix/aliases:/etc/postfix/aliases
        - ./postfix_server/etc/postfix/main.cf:/etc/postfix/main.cf
        - ./postfix_server/etc/postfix/master.cf:/etc/postfix/master.cf
        - ./postfix_server/etc/postfix/generic:/etc/postfix/generic
        - ./postfix_server/etc/postfix/virtual:/etc/postfix/virtual
        - ./postfix_server/etc/postfix/mysql_virtual_alias_maps.cf:/etc/postfix/mysql_virtual_alias_maps.cf
    links:
        - database:database

database:
    image: mysql:5.5
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=postfix
        - MYSQL_USER=postfix
        - MYSQL_PASSWORD=password
    volumes:
        - ./database/mysql:/var/lib/mysql

client1:
    build: postfix_client
    volumes:
        - ./postfix_client/etc/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    links:
        - postfix:zz2postfixproject.fr

webserver:
    build: apache
    ports:
        - "80:80"
    volumes:
        - ./apache/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
        - ./apache/php.ini:/etc/php5/cli/conf.d/30-custom.ini
        - ../website:/var/www/html/
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - database:database

webserver_newsletter:
    build: apache+mail
    ports:
        - "8888:80"
    volumes:
        - ../website-newsletter:/var/www/html/
        - ./apache+mail/etc/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - postfix:zz2postfixproject.fr

phpmyadmin:
    image: corbinu/docker-phpmyadmin:4.2.7.1
    ports:
        - "8080:80"
    environment:
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=rootpassword
    links:
        - database:mysql
