# dc rm -f && dc build && dc up

postfix:
    build: postfix_server
    hostname: localhost
    domainname: localdomain
    ports:
        - "25:25"
        - "80:80"
    volumes:
        - ./postfix_server/etc/postfix/aliases:/etc/postfix/aliases
        - ./postfix_server/etc/postfix/main.cf:/etc/postfix/main.cf
        - ./postfix_server/etc/postfix/master.cf:/etc/postfix/master.cf
        - ./postfix_server/etc/postfix/generic:/etc/postfix/generic
        - ./postfix_server/etc/postfix/virtual:/etc/postfix/virtual
        - ./postfix_server/etc/postfix/mysql_virtual_alias_maps.cf:/etc/postfix/mysql_virtual_alias_maps.cf
    links:
        - database:database

database:
    image: mysql:5.5
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=postfix
        - MYSQL_USER=postfix
        - MYSQL_PASSWORD=password

client1:
    build: postfix_client
    volumes:
        - ./postfix_client/etc/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
        - ./postfix_client/etc/ssmtp/revaliases:/etc/ssmtp/revaliases
    links:
        - postfix:postfix

#phpmyadmin:
#   image: corbinu/docker-phpmyadmin
#   ports :
#    - "8080:80"
#   environment:
#    - MYSQL_USERNAME=root
#    - MYSQL_PASSWORD=password
#   links:
#    - database:mysql