postfix:
    build: postfix_server
    volumes:
        - ./postfix_server/etc/aliases:/etc/aliases
        - ./postfix_server/etc/postfix/main.cf:/etc/postfix/main.cf
        - ./postfix_server/etc/postfix/generic:/etc/postfix/generic
#        - ./postfix_server/run.sh:/opt/run.sh
